### ISSUE TITLE
Spoiler-free version

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#11]
Please can you consider making a version of "Find a Friend" that doesn't include the "Lvl 0" entries for social links you are yet to initiate?

![P4G 2020-12-27 17-53-24](https://user-images.githubusercontent.com/53123052/103176796-c5f88b00-486c-11eb-8d37-16c52ab2789d.png)

It could be argued that these "Lvl 0" entries push the mod across the fine line from QOL into spoiler-territory. Not only do they reveal the existence of a new link, but they tell you the person's name and warp you directly to them. At this point, they're not even "friends" to find yet! They're strangers! :) Especially as a new player, part of the fun is discovering these links for yourself.

For this reason, I think it would be better if there was a version of "Find a Friend" that only allowed you to find these links once you reach rank 1.

Thanks!

**Comment by AnimatedSwine37** [comment]
I see how this can get into spoiler-territory and I definitely will make a spoiler-free option. 

However, the reason I wanted them to show at level 0 is that I feel some social links can easily be missed altogether. For example, I never knew Naoki existed until I started making these mods and a friend of mine played through the entire game without knowing Hisano existed. 

I'm thinking of making a version which is a middle ground, maybe not naming them or giving a vague description of them or something. If you have any ideas of how this could be done/if it should I'd love to hear them.

**Comment by AnimatedSwine37** [comment]
Actually, after some thinking, I don't think I will make a middle ground version for now at least.
I think the game does sufficiently point you towards most social links (maybe with a few exceptions) so I'll leave it as a full spoilers and spoiler free version.
Also, making this might be a lot of work for not much payout. Unlike the way the pages are done in the mod menu and others (I think), I have everything under one selection and use a mask to filter it down, making the 'dynamic' pages possible. By this I mean depending on the conditions almost every link can be on each page in a variety of combinations.
If I were to do some kind of middle ground version I would probably have to duplicate most options, doubling the size of the selection. As masks work using an integer representing a bit (2^x) I think the mask may hit the integer limit (2^31) which I would probably have to go over to mask out enough options. There is probably a way to work around this but frankly I wouldn't want to try and work it out.

Anyway, I've made a spoiler-free option that will release with 1.6
