### ISSUE TITLE
Rise location - Classroom Building, 1F

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#15]
**Game version:** Persona 4 Golden v1.1 (REV 2033)
**Mod version:** Find a Friend (v1.6)

## Issue

When Rise is available in Classroom Building, 1F, travelling to her location with "Find a Friend" places you a notable distance away from her compared to other social links. If possible, please can Yu's location be adjusted so the player is placed closer to Rise?

![P4G 2020-12-27 12-30-09](https://user-images.githubusercontent.com/53123052/103230272-ebe56480-492c-11eb-8ad2-176419591760.png)

Travelling to Naoki in Shopping District, North is similar. If that could be adjusted too, that would be great but Rise is definitely more noticeable.

![P4G 2020-12-27 12-36-22](https://user-images.githubusercontent.com/53123052/103230448-63b38f00-492d-11eb-8bfd-3e9fd8421307.png)

Thanks!

**Comment by AnimatedSwine37** [comment]
I altered Rise's tp point to be much closer (still not as close as some but as good as possible), I'm not sure how I thought what it was previously was the best option.

Unfortunately, I can't do anything about Naoki as there are no points closer to him than the current one. Basically, the way it works is there are a number of set teleport points in each field that I suppose are hardcoded and I just have to work with what I'm given. It could be interesting though, to see if these could be changed or more could be added. I really don't know how the fields work though.
