### ISSUE TITLE
Incorrect Entries - April

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#18]
### Issues
Went through the whole month of April specifically looking for incorrect entries in FAF. These are the only two remaining as far as I can tell. Attached clean test saves for both.

**04/22, Evening - Yosuke (Shopping District, North)**
Menu entry but not actually there.

![image](https://user-images.githubusercontent.com/53123052/105641918-706cc980-5e7e-11eb-9f3d-e45f3226988e.png)
Save: [04.22, Friday - Evening.zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/5863183/04.22.Friday.-.Evening.zip)

**04/25, Evening - Yumi (Shopping District, South)**
Menu entry but not actually there.

![image](https://user-images.githubusercontent.com/53123052/105643384-70bd9280-5e87-11eb-8065-33f4672d5d1b.png)
Save: [04.25, Monday - Evening.zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/5863180/04.25.Monday.-.Evening.zip)

**Comment by AnimatedSwine37** [comment]
Both of these were caused by one oversight where I didn't check if time had already been spent with an s.link during the daytime as you can't spend both day and night with one. This should now be fixed for all s.links that you can spend time with at night.
