### ISSUE TITLE
Incorrect Entries - May

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#19]
### Issues

Some incorrect entries in FAF for May. Attached clean test saves. You can find the other saves from this playthrough (if useful) [in my save archive](https://drive.google.com/drive/folders/1gbqQXQJ1LYFQttry0k2yix_eeh3UkDYp).

**05/20, Evening - Yosuke (Shopping District, North)**
Menu entry but not actually there.
Save: [05.20, Friday - Evening.zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/5890095/05.20.Friday.-.Evening.zip)

![image](https://user-images.githubusercontent.com/53123052/106184163-15e2ae80-6199-11eb-8aed-e76b4edfa359.png)
![image](https://user-images.githubusercontent.com/53123052/106184187-1b3ff900-6199-11eb-8d81-b5d9156445e4.png)

**05/20, Evening - Yukiko (Shopping District, South)**
Menu entry but not actually there.
Save: Same as above.

![image](https://user-images.githubusercontent.com/53123052/106184377-5d693a80-6199-11eb-8d4f-b7eb1bc3efed.png)
![image](https://user-images.githubusercontent.com/53123052/106184313-46c2e380-6199-11eb-8108-b1a45aecd397.png)

**Comment by AnimatedSwine37** [comment]
Thanks for this. It turns out party members can't show at night if you're currently investigating.
