### ISSUE TITLE
Incorrect Entries - July 29th Evening

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#22]
_Version: Custom Sub Menu v1.11 / Find a Friend v1.9_

### Issues

Unfortunately I've found a couple more incorrect entries on July 29th, Evening. 
Possibly relevant: this day is during the Mitsuo investigation, when you're walking around town talking looking for clues in the daytime.

Save attached. More for the surrounding days can be found in [my save archive](https://drive.google.com/drive/folders/1gbqQXQJ1LYFQttry0k2yix_eeh3UkDYp).

[07.29, Friday - Evening.zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/6055784/07.29.Friday.-.Evening.zip)

**Yosuke (Shopping District, North)**
Menu entry but not actually there.

![image](https://user-images.githubusercontent.com/53123052/109402493-51b29480-794e-11eb-8c2e-817ccadfa5e0.png)

**Yukiko (Shopping District, South)**
Menu entry but not actually there.

![image](https://user-images.githubusercontent.com/53123052/109402535-9dfdd480-794e-11eb-9623-af779e2d5f74.png)

**Comment by AnimatedSwine37** [comment]
Fortunately this isn't actually an issue with Find A Friend, but rather an issue with custom sub menu. When it last updated find a friend was in between 1.9 releasing, so half of the fixes in 1.9 (including this) weren't included in it. I'll make a pull request with the properly updated FAF and hopefully it will be fixed on that end soon.
