### ISSUE TITLE
Daisuke/Kou appearing when they shouldn't

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#26]
### Issue
I've now worked through the whole game up to October with FAF, checking and documenting _every single day_ to see exactly who's available when to try and narrow this down. [Document here](https://docs.google.com/spreadsheets/d/1e1L5So10aP3QPopm0zbu0JP7L9l06MtqHYEU_1yha0I/edit?usp=sharing).

I can finally say with some certainty that **the issue is related to whether you have saved Naoto or not**! The last day you can save Naoto by is October 5th.

I can now also confirm what I saw when I tested this back in January:
- **10/03 (October 3rd) is the first evening this issue starts occurring.**
[10.03, Monday - Evening.zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/6211345/10.03.Monday.-.Evening.zip)

On this save the Strength link is at Rank 8 and Naoto **has** been saved. Daisuke is selectable from FAF but when you warp to him, he's not there.

HOWEVER, on this save Naoto **has not** been saved. If I perform the same action, Daisuke is there:
[October 3rd (NAOTO NOT SAVED).zip](https://github.com/AnimatedSwine37/Find-a-Friend/files/6211536/October.3rd.NAOTO.NOT.SAVED.zip)

![image](https://user-images.githubusercontent.com/53123052/112626222-d39bbd80-8e27-11eb-8b48-de798af633e6.png)

Whether there are other S. Links affected by other deadline flags, I can't be certain. I haven't seen anything else like it, but I might go back and check.

Cheers

**Comment by AnimatedSwine37** [comment]
Whilst this is closed as I have fixed the issue I want to note one thing.
I fixed this by always disabling the option from October 5 to January 1 (as well as accounting for the varying availability on October 3rd depending on whether Naoto is saved or not).
Whilst this appears to work in my testing (mostly using the mod menu to switch between dates) they may be available sometime in between this range (as they become available again in January based on my own clean save). Although I'm fairly confident this isn't the case as from my own clean playthrough I'm fairly sure they were never available during this time (although I may be wrong).
