### ISSUE TITLE
Sports club and cultural club options were missing at level 0

### ISSUE THREAD

**Issue by TekkaGB** [AnimatedSwine37/Find-a-Friend#3]
https://github.com/ShrineFox/Persona-4-Golden-Mod-Menu/commit/ebb79b3d01eb069514391f1baf6da74465714d34

I think I fixed this issue in this commit to the custom square menu.  I made it so both Kou/Daisuke and Ayane/Yumi showed up as options at level 0.  Once one is greater than level 0 only one of them shows.  I also made it so at level 0 they spawn in front of their respective club rooms.

**Comment by AnimatedSwine37** [comment]
Updated this to be the same as what you have in the custom square menu with [commit ](https://github.com/AnimatedSwine37/Find-a-Friend/commit/da66b7d35e4a991bce96d0d4a5b3f956750cb07a).
Also, I fixed what I think is a typo in the square menu's version [here](https://github.com/ShrineFox/Persona-4-Golden-Mod-Menu/commit/ebb79b3d01eb069514391f1baf6da74465714d34#r45440305).
