### ISSUE TITLE
Adachi Issues

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#4]
**Game version:** Persona 4 Golden v1.1 (REV 2033)
**Mod version:** P4G Custom Square Menu (v1.6)

### Issue 1
**Adachi is available from the "Find a Friend" menu on days when you can't actually hangout with him.**

![P4G 2020-12-26 14-08-21](https://user-images.githubusercontent.com/53123052/103153105-e1d53180-4785-11eb-9d7a-5cc2f0bc52ff.png)

In this example, Adachi is rank 5 on the evening of 09/21. If you speak to him, he will tell you he's working overtime and unable to hangout right now.

Whether Adachi is available during the day or at night is dependent on his social link rank. Please can the options reflect this? If he's not available at night, please don't show him in the menu.

His availability is as follows:
Rank 1 > 2 - Daytime, Junes
Rank 2 > 3 - Nighttime, Gas Station
Rank 3 > 4 - Nighttime, Gas Station
Rank 4 > 5 - Nighttime, Gas Station
Rank 5 > 6 - Daytime, Junes

(More info here: https://www.rpgsite.net/feature/9830-persona-4-golden-adachi-social-link-choices-unlock-guide)

### Issue 2
**If you use the "Find a Friend" menu to warp to Adachi's location in the evening when he is outside the petrol station, you will clip inside his model.**

![P4G 2020-12-26 14-08-39](https://user-images.githubusercontent.com/53123052/103153157-80fa2900-4786-11eb-9756-1ff00d9cd0b6.png)

Please can the warp location be adjusted so this doesn't happen?

Thank you for your time!

**Comment by AnimatedSwine37** [comment]
I've updated it so he should now only show when he is actually available according to the availabilities you've given me. 
I haven't tested every rank but believe it should work properly for all; if you find he shows when he shouldn't be please tell me. 
I've also updated the warp location so he doesn't clip.

Also, thanks for all of the helpful issues now I have a v1.5 to release!
