### ISSUE TITLE
Nanako/Dojima unavailable from the "Find-a-Friend" menu

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#5]
**Game version:** Persona 4 Golden v1.1 (REV 2033)
**Mod version:** P4G Custom Square Menu (v1.6)

### Issue
**Neither Nanako or Dojima are available from the "Find-A-Friend" menu.**

![P4G 2020-12-26 15-03-31](https://user-images.githubusercontent.com/53123052/103153871-c8cf7f00-478b-11eb-9fbc-cd2d293e4b2e.png)

Is there a reason for their exclusion? For consistency, please can they be added? It would be great to be able to use this menu to travel straight home to them when elsewhere at night.

Thanks for your time.

**Comment by AnimatedSwine37** [comment]
Tbh I was just being lazy, I figured you always see them anyway (as you always start the night at your house) so they weren't really necessary. 
But now I've added them for that good consistency.
