### ISSUE TITLE
Rise not always listed in the "Hangout with a friend" menu

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#8]
**Game version:** Persona 4 Golden v1.1 (REV 2033)
**Mod version:** P4G Custom Square Menu (v1.6)

### Issue

I've noticed that Rise isn't always available in the Find a Friend menu for some reason. See screenshot below.

![P4G 2020-12-26 20-56-22](https://user-images.githubusercontent.com/53123052/103159077-07c9f880-47bd-11eb-8543-01ef5445f84a.png)

In this example, the date is 10/16. Rise's current rank is 6.
Rise is available to hang out with if you speak to hear but doesn't show up in the menu no matter where you are on the map.

Do you know why this could be?

Thanks

**Comment by AnimatedSwine37** [comment]
Thanks for telling me about this. It turns out I was checking the wrong flag for Rise, anytime she would show would just be a coincidence as she overlapped with the incorrect flag I guess.
