### ISSUE TITLE
Yukiko bugs

### ISSUE THREAD

**Issue by rudiger-gh** [AnimatedSwine37/Find-a-Friend#9]
**Game version:** Persona 4 Golden v1.1 (REV 2033)
**Mod version:** Find a Friend (v1.5)

### Issue 1

**When selecting Yukiko from the "Find a Friend" menu, you will not be warped to her location as expected.
Instead, a sub-menu option will appear with an "Others..." option. Selecting this dismisses the menu entirely. If you hit the Esc key while in this sub-menu, the game will transport you to Adachi's location (whether he's actually there or not...).**

![P4G 2020-12-27 12-02-22](https://user-images.githubusercontent.com/53123052/103170675-ff65d200-483d-11eb-877b-67bdf5ccd62d.png)

![P4G 2020-12-27 12-02-11](https://user-images.githubusercontent.com/53123052/103170583-24a61080-483d-11eb-9f37-21e41293bedc.png)

As far as I can tell, this bug was introduced in the latest version (v1.5). In my example pictured, the date is 09/22. Yukiko is rank 6 and her location is Classroom Building, 1F. 

It doesn't appear to matter where Yukiko is located, however. I haven't been able to get the option to work as intended no matter where she or I are.

**Edit:** Updated the issue to include the Adachi behaviour.

As mentioned above, if you hit the Escape key while in that sub-menu (don't know the controller equivalent, sorry), the game will try and take you to Adachi. Screenshot below.

![P4G 2020-12-27 12-41-41](https://user-images.githubusercontent.com/53123052/103171100-57ea9e80-4841-11eb-8257-08126778f524.png)

### Issue 2

**When using the "Find a Friend" menu to hang out with Yukiko in Classroom Building, 1F, you will clip into her model.**

![P4G 2020-12-26 19-18-28](https://user-images.githubusercontent.com/53123052/103170644-aa29c080-483d-11eb-8eee-f3303c22eb30.png)

I can't actually check this issue in v1.5 of the mod because of Issue 1 (above), but it was present in v1.4. Should this issue still exist, please can you adjust Yu's location so he doesn't clip into Yukiko's model here?

Thanks!

**Comment by AnimatedSwine37** [comment]
These should both be fixed now.
